### ISSUE TITLE
Label file empty: possible race condition?

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb#1363] opened 2022-08-12 09:59 UTC
In the Python client tests we found out that sometimes the tests break because a label file can't be read. This could be related to us removing the lock in `terminusdb-store` in the label store.

See for instance this test failure: https://github.com/terminusdb/terminusdb-client-python/runs/7803862949?check_suite_focus=true

```
{
    "err": "API Error api:message Error: rust_io_error(\"expected label file to have two lines. contents were ([])\")
}
```

**Comment by matko** [comment] 2022-08-15 10:56
Duplicate of #1369 which contains more info.

**Closed by matko** 2022-08-15 10:56 UTC
Labels: bug
