### ISSUE TITLE
Error whenever trying to delete a document.

### ISSUE THREAD

**Issue by chonymony** [terminusdb/terminusdb#2102] opened 2024-02-22 21:10 UTC
Whenever trying to delete a document, with WOQL or in UI getting the following error:

![image](https://github.com/terminusdb/terminusdb/assets/2424099/375c3f7e-36bd-4e9c-a0bf-7a6af753d53e)

`SERVER ERROR: Error: rust_error(panic("called `Option::unwrap()` on a `None` value")) [48] delete_document(<GetDocumentContext>,transaction_object{commit_info:commit_info{},descriptor:branch_descriptor{branch_name:"main",repository_descriptor: ...},inference_objects:[],instance_objects:[...],parent:transaction_object{descriptor: ...,inference_objects:[],instance_objects: ...,parent: ...,schema_objects: ...},schema_objects:[...]},'terminusdb:///data/Mensaje/fmUo5z5wFXOAvYG6',true) [44] freeze(true,woql_compile:delete_document(...,'terminusdb:///data/Mensaje/fmUo5z5wFXOAvYG6')) at /usr/lib/swipl/boot/attvar.pl:116 [43] '<meta-call>'('<garbage_collected>') <foreign> [42] findall_loop(_27536,'<garbage_collected>',_27540,[]) at /usr/lib/swipl/boot/bags.pl:99 [41] setup_call_catcher_cleanup('$bags':'$new_findall_bag','$bags':findall_loop(_27594,...,_27598,[]),_27576,'$bags':'$destroy_findall_bag') at /usr/lib/swipl/boot/init.pl:679 [37] '<meta-call>'('<garbage_collected>') <foreign> [36] call('<garbage_collected>') at /usr/lib/swipl/boot/init.pl:502 [35] catch(database:call(...),fail_transaction,database:(_27724=true)) at /usr/lib/swipl/boot/init.pl:565 [34] database:with_transaction_(query_context{all_witnesses:false,authorization:'terminusdb://system/data/User/auth0%7C6534209e5978d3f24c7b1c0b',bindings:[...],commit_info:json{author:"terminusdb.brush779@simplelogin.com",message:"test commit"},default_collection:branch_descriptor{branch_name:"main",repository_descriptor: ...},files:[],filter:type_filter{types: ...},prefixes:_27848{'@base':"terminusdb:///data/",'@schema':"terminusdb:///schema#",'@type':'Context',api:'http://terminusdb.com/schema/api#',json:'http://terminusdb.com/schema/json#',owl:'http://www.w3.org/2002/07/owl#',rdf:'http://www.w3.org/1999/02/22-rdf-syntax-ns#',rdfs:'http://www.w3.org/2000/01/rdf-schema#',sys:'http://terminusdb.com/schema/sys#',vio:'http://terminusdb.com/schema/vio#',woql:'http://terminusdb.com/schema/woql#',xdd:'http://terminusdb.com/schema/xdd#',xsd:'http://www.w3.org/2001/XMLSchema#'},selected:[],system:transaction_object{descriptor: ...,inference_objects:[],instance_objects: ...,schema_objects: ...},transaction_objects:[...],update_guard:_27818,write_graph:branch_graph{branch_name:"main",database_name:"choni_db_stg",organization_name:"chonymony",repository_name:"local",type:instance}},query_response:(...,...),_27766,[]) at /app/terminusdb/src/core/transaction/database.pl:245 [33] setup_call_catcher_cleanup(database:pre_transaction_tabling,database:with_transaction_(...,...,_28036,[]),_28014,database:post_transaction_tabling) at /usr/lib/swipl/boot/init.pl:679 [29] query_response:run_context_ast_jsonld_response('<garbage_collected>','<garbage_collected>',no_data_version,_28086,_28088,'<garbage_collected>') at /app/terminusdb/src/core/query/query_response.pl:28 [27] '<meta-call>'('<garbage_collected>') <foreign> [26] catch(routes:(...,...),error(rust_error(...),context(_28184,_28186)),routes:do_or_die(...,...)) at /usr/lib/swipl/boot/init.pl:565 [25] catch_with_backtrace('<garbage_collected>','<garbage_collected>','<garbage_collected>') at /usr/lib/swipl/boot/init.pl:645 Note: some frames are missing due to last-call optimization. Re-run your program in debug mode (:- debug.) to get more detail.`

document deletion is expected.

**Comment by Tra5is** [comment] 2024-02-23 00:10
I also saw that exception recently. Eventually I discovered it would occur when I was trying to delete something that didn't exist, or the Id I was using didn't match. The matching is case sensitive.

**Comment by chonymony** [comment] 2024-02-23 01:15
The funny thing is that i'm using the dashboard delete button instead of WOQL. So maybe is some sort of issue with the UI.

**Comment by GavinMendelGleason** [comment] 2024-02-23 09:12
We moved to a faster delete in rust, and I think this may have been the cause, we'll try to track down.

**Comment by matko** [comment] 2024-02-23 10:17
Is it possible for you to share your org/db name on TerminusCMS for a database that is having this problem? I would very much like to have a look, since I can't seem to reproduce this locally at all.

**Comment by chonymony** [comment] 2024-02-23 16:41
> Is it possible for you to share your org/db name on TerminusCMS for a database that is having this problem? I would very much like to have a look, since I can't seem to reproduce this locally at all.

Sure, chonymony/choni_db_test_J

**Comment by chonymony** [comment] 2024-02-24 00:17
Keep getting the errors, now whenever trying to update a document. It's worth to mention the objects are different type and schema, the only thing they got in common is a JSON property. I've been facing errors whenever i try to leverage the property type json. Updating, deleting, in the UI editor, wherever it's related to a JSON it's inconsistent.
![image](https://github.com/terminusdb/terminusdb/assets/2424099/5451ee69-8ab4-468e-9a04-60d712f74448)

**Comment by adamc-sp** [comment] 2024-03-07 15:27
I've been seeing this when trying to combine UI usage and API usage. I have setup a system to automatically make a stub document to be edited later, but some documents are created within the UI itself and some came from bulk uploading using the API ~400 documents.

It looks like the documents created as stubs cannot be edited or deleted as they hit this error, but all other documents can be edited/deleted fine.

I did some more investigation into whether it was an issue with the schema or the population methods I was using and this seems to work fine when using the same schema with a different data product temporarily, e.g. I created a new data product with the same schema and inserted new stub documents which could then be deleted fine. But after leaving it a day then new stub documents cause this panicking.

I have been using sub-documents so maybe this is related to the inconsistencies with using the JSON property?

**Comment by chonymony** [comment] 2024-03-11 23:08
> @chonymony We currently have a pre-release of v11.1.12 up on production which I believe fixes the issue. Could you please try again?

Hello!, just tried and apparently error continues :(
```
{
  "@type": "deleted_object_still_referenced",
  "object": "terminusdb:///json/JSON/SHA1/89d736b5695f4ef1c3f03a189782976175aad538",
  "predicate": "terminusdb:///schema#contenido",
  "subject": "terminusdb:///data/Mensaje/VbN8jhYrytZ4BkcP"
}
```
![image](https://github.com/terminusdb/terminusdb/assets/2424099/3d4e45e9-7ee2-4dae-8e5d-2dd9bf0c8260)

**Comment by chonymony** [comment] 2024-03-11 23:11
Deleting references from WOQL then deleting the doc still works tho.

![image](https://github.com/terminusdb/terminusdb/assets/2424099/3fd0895a-818c-4a44-be62-7f836c066362)

**Comment by matko** [comment] 2024-03-12 16:13
It looks like the original issue is fixed then, and unfortunately, it appears you're running into another issue now.

I'm closing this issue and we'll be properly releasing a new version of terminusdb tomorrow. Could you please submit another bug report specifically for your case of json object deletion?

**Closed by matko** 2024-03-12 16:13 UTC
Labels: bug

**Comment by hoijnet** [comment] 2024-03-12 20:01
Adding a reference to #2090 which was about the same core issue, it can be closed too I think! Great work!

**Comment by alexander-mart** [comment] 2024-12-22 22:04
> Could you please submit another bug report specifically for your case of json object deletion?

@matko Separate issue about `deleted_object_still_referenced` error: https://github.com/terminusdb/terminusdb/issues/2121

**Comment by hoijnet** [comment] 2025-07-12 09:36
FYI:

The arbitrary JSON functionality has now been marked as experimental in the [schema reference guide](http://localhost:3000/docs/schema-reference-guide/#json-types-sys-json-and-sys-json-document-experimental-and-unsupported). Sorry for the troubles!

We recommend that all values stored in TerminusDB are typed with specific datatypes.

**Comment by hoijnet** [comment] 2025-07-12 12:19
Correct link now provided: [schema reference guide](https://terminusdb.org/docs/schema-reference-guide/#json-types-sys-json-and-sys-json-document-experimental-and-unsupported)
