### ISSUE TITLE
Unhandled exception `key_has_unknown_prefix/1`

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#845] opened 2021-12-13 15:06 UTC
```shell
$ curl -X POST -u admin:root 'http://localhost:6363/api/document/_system?author=admin&message=test' \ 
   -d '{ "@type": "foo:User" }' -H 'Content-Type: application/json'
```

```
[ERROR] 2021-12-13T15:57:36.212902+01:00 [Exception] error(key_has_unknown_prefix("foo:User"),context(prolog_stack([frame(48,call(system:throw/1),throw(error(key_has_unknown_prefix("foo:User"),_14956))),frame(46,pred_line("catch/3",'/home/gavin/.swivm/versions/v8.4.1/lib/swipl/boot/init.pl':562),catch(api_document:do_or_die(...,...),error(key_has_unknown_prefix("system:User"),_15012)
```

Just needs to be caught and handled.

**Comment by matko** [comment] 2022-06-28 14:19
Duplicate of #804.

**Closed by matko** 2022-06-28 14:19 UTC
Labels: bug
