### ISSUE TITLE
Incorrectly escaped string response in TerminusDB 11 for context comment

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1700] opened 2023-02-03 14:43 UTC
**Describe the bug**
`\n` is encoded as `\\n` in the context comment field in the response

**To Reproduce**
1. Have a comment field with `\n` in the data product context
2. Retrieve it `api/user_organizations`
4. See issue in screenshot

**Expected behavior**

**Screenshots**
<img width="522" alt="image" src="https://user-images.githubusercontent.com/144317/216631256-6787921e-cb9a-4cd1-9894-a179095c9558.png">

**Info (please complete the following information):**
 - OS: TerminusX/DFRNT

**Additional context**
N/A

**Comment by hoijnet** [comment] 2023-02-05 15:43
The same issue is there for strings with newlines in document responses. Seems like it is actually a regression related to #1507

**Comment by rrooij** [comment] 2023-02-05 20:03
Interesting. Thanks for reporting! I am not able to reproduce it locally so it seems to be a problem specifically related to TerminusX.

When running locally with the latest `main`:

```
$ curl -u admin:root 'localhost:6363/api/db/admin/test10' -X POST -H 'Content-Type: application/json' -d '{"label": "hello", "comment": "hello \nworld"}'
$ curl -u admin:root 'localhost:6363/api/db/admin/test10?verbose=true | jq
```

I get back:
```json
{
  "@id": "UserDatabase/ef41edf6567021f7020e36836e0d9b4b52b5893ed49674b0babde47f0feaf58c",
  "@type": "UserDatabase",
  "branches": [
    "main"
  ],
  "comment": "hello \nworld",
  "creation_date": "2023-02-05T19:54:43.722Z",
  "label": "hello",
  "name": "test10",
  "path": "admin/test10",
  "state": "finalized"
}
```

Same when doing the user_organizations call:

```
curl -u admin:root 'localhost:6363/api/user_organizations' | jq
```

```json
[
  {
    "@id": "Organization/admin",
    "@type": "Organization",
    "databases": [
      {
        "@id": "SystemDatabase/system",
        "@type": "SystemDatabase",
        "name": "_system"
      },
      {
        "@id": "UserDatabase/a761417280549982c24ac088dbdd49e6b52492dd6399eeb76f5ed76d7d1fb490",
        "@type": "UserDatabase",
        "comment": "test",
        "creation_date": "2023-01-30T17:00:09.089Z",
        "label": "test",
        "name": "test",
        "state": "finalized"
      },
      {
        "@id": "UserDatabase/ef41edf6567021f7020e36836e0d9b4b52b5893ed49674b0babde47f0feaf58c",
        "@type": "UserDatabase",
        "comment": "hello \nworld",
        "creation_date": "2023-02-05T19:54:43.722Z",
        "label": "hello",
        "name": "test10",
        "state": "finalized"
      }
    ],
    "name": "admin"
  }
]
```

I can reproduce your problem when creating a new database in the TerminusX dashboard. In the description/comment field, when I'm pressing "normal" enters instead of putting newlines, they don't escape and show up as newlines. I'm not sure if this is intended behavior or not, as you can insert real newlines as well in the browser.

I will discuss it with the team as well. Thanks for reporting! :) 

When creating in the UI both by putting raw `\n` as using normal enters:

```json
{
	"databases": [
		{
			"@id": "UserDatabase/SomeID",
			"@type": "UserDatabase",
			"comment": "Hello\\n\nWorld\n\nEnter",
			"creation_date": "2023-02-05T19:58:24.186Z",
			"label": "TestDataProductNewLines",
			"name": "test_data_product_newlines",
			"state": "finalized"
		}
	]
}
```

As you can see, my real newlines in the UI are not double escaped whereas the \n is.

**Comment by hoijnet** [comment] 2023-02-05 20:19
It seems it works correctly when working with new documents directly in TerminusX 11. I have not changed the existing products where I see the incorrect behaviour. Could it be the upgrade process?

This is with data products in TerminusX 11, and thus they were upgraded. I tried adding documents with enter in them, and new documents behave correctly. So this seems to be affecting upgraded products, when reading strings with enter in them and double quotes I think.

**Comment by rrooij** [comment] 2023-02-05 20:36
Thanks for trying it yourself on TerminusX 11 as well.

I could reproduce the entire issue without using conversion in the previous version of TerminusDB (v10.1.11).

The script to reproduce:


```bash
mkdir old_db
sudo docker run --rm -it -v $(pwd)/old_db:/app/terminusdb/storage/db terminusdb/terminusdb-server:v10.1.11 /bin/bash -c \
        './terminusdb store init && ./terminusdb db create admin/test --comment="hello\nworld" --label=test && ./terminusdb db list --json --verbose'
```

**Comment by rrooij** [comment] 2023-02-05 22:08
Another script using TerminusDB v10.1.11 to reproduce the problem (using the API):

```
DB_DIR="old_db_$RANDOM"
mkdir "$DB_DIR"
sudo docker run -d -it -p 6363:6363 --rm --name=terminusdb-temp \
        -v $(pwd)/"$RANDOM":/app/terminusdb/storage/db terminusdb/terminusdb-server:v10.1.11 /bin/bash -c \
        './terminusdb store init && ./terminusdb db create admin/test --comment="hello\nworld" --label=test && ./terminusdb serve';
sleep 10
curl -u admin:root 'localhost:6363/api/db?verbose=true'
sudo docker stop terminusdb-temp
```

**Comment by hoijnet** [comment] 2023-02-08 13:15
I tried cloning a data product from Terminus11 (hosted at TerminusCMS) into Terminus10 to continue working on it in the production environment, but the context comment with the incorrect `\n` encoded as `\\n` follows through the clone, indicating the newline encoding is perhaps fairly far down the layers as it also affects cloning.

Thought I'd mention it as this makes it hard to work with the data products in the 11 release until resolved.

**Comment by rrooij** [comment] 2023-02-08 13:36
The extra escape when cloning to TerminusDB10 is indeed strange. However, it is not possible to clone between those two versions because of the new storage format which is incompatible with the old storage format. We do however want to improve the error reporting in this regard.

**Comment by hoijnet** [comment] 2023-02-10 20:43
After some more thinking and creating a new data product in TerminusDB 11, I suspect the double encoded `\\n` are from the upgrade script as things are working smoothly in data products produced by TerminusDB 11. Could you verify what happens upon upgrade of strings with newlines? I believe that is where the issue might lie?

If so, how to fix the already upgraded data products?

**Comment by matko** [comment] 2023-07-17 10:57
At this point, due to how much time has passed and the mixture of old and new data currently in the system graph, we think that fixing any remaining doubly encoded strings in database labels and comments will have to be a manual operation, rather than an automatic fixup script. I'm therefore closing this issue. If you still have data products that have their label or comment wrongly escaped, please let us know and we'll fix it.

**Closed by matko** 2023-07-17 10:57 UTC
Labels: bug

**Comment by hoijnet** [comment] 2023-08-09 15:42
I have not seen any more, all is in order =)
