### ISSUE TITLE
Can't update enum in TerminusX Dashboard

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#754] opened 2021-11-04 12:06 UTC
**Describe the bug**
When creating enum in TerminusX dashboard, it asks me to enter a valid key, after it has accepted the input.

**To Reproduce**
1. Go to home
2. Create new data product id:  myEnum2, name: data
3. Add enum id:test, value: test
4. Click add value
5. Save is successful
6. Select test enum
7. Go to Values
8. Add value "test2"
9. Error is thrown

**Expected behavior**
The enum value should be updated. It seems there is a problem with loading the enum. Reloading the product_models page yields the following in the console:
```
query run error Error: API Error @type api:WoqlErrorResponse api:message Not well formed WOQL JSON-LD api:status api:failure Code: 400 url: https://cloud.terminusdb.com/SecondZebra/api/woql/SecondZebra/myEnum2/local/branch/main
    at tdb-dashboard.min.js:2
```

I can remove the enum, but as long as the enum is there, I can no edit my schema.

**Screenshots**

![image](https://user-images.githubusercontent.com/144317/140309995-219060e7-d18e-4f1c-962d-20d8d7e6249a.png)

**Info (please complete the following information):**
 - OS: macOS with Edge Chromium
 - TerminusX

**Additional context**

**Comment by spl** [comment] 2021-11-15 12:01
We're currently working on this on TerminusX.

**Comment by hoijnet** [comment] 2021-11-16 12:29
Thanks for the work to make them work better in the user interface! 

Looks like enums are working better now, tested today. See latest issue on Enums too, posted today, where documentation fields are not working in TerminusDB (i.e. in the document interface), also not working in TerminusX (likely same issue).

**Comment by Francesca-Bit** [comment] 2021-11-16 14:34
I tested the problem is in TerminusDB, the database doesn't save the documentation for an enum 
To riproduce:
//add this document  POST CALL
{@id: "EnumTest", @type: "Enum", @value: ["val01"], @documentation: {@comment: "hello"}}

//get the document back GET DOCUMENT CALL 
{"@id":"EnumTest", "@type":"Enum", "@value": ["val01" ]} 
no documentation

**Comment by Francesca-Bit** [comment] 2021-11-16 14:46
I close this issue for the interface

**Closed by Francesca-Bit** 2021-11-16 14:46 UTC
Labels: bug
