### ISSUE TITLE
Update sub document doesn't work 

### ISSUE THREAD

**Issue by KittyJose** [terminusdb/terminusdb#412] opened 2021-08-13 15:27 UTC
**Describe the bug**
Update sub document doesn't work 

**To Reproduce**
```json
{
   "@id":"Organization_kitty",
   "@type":"Organization",
   "creation_date":"2011-01-01T01:00:37Z",
   "invitations":[
      {
         "@id":"Invitation_86b7ca4ee3bf6da3cb4a27d56005b862e207f653",
         "@type":"Invitation",
         "email_to":"kitzkan@gmail.net",
         "invited_by":"User_MASS",
         "note":"sure",
         "status":"pending"
      }
   ],
   "organization_name":"kitty",
   "owned_by":"User_MASS",
   "status":"active"
}
```

For above invitation (subdocument) if you alter any property email or invited_by. No response comes back from database and hence the update mever happens

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/54106287/129382379-7ca25237-12fe-416a-af07-e0169743cbca.png)

**Comment by spl** [comment] 2021-08-16 13:47
Okay, so a simple subdocument update does work:

`schema.json`

```json
{"@id":"Child","@type":"Class","@key":{"@type":"Random"},"@subdocument":[],"name":"xsd:string"}
{"@id":"Parent","@type":"Class","@key":{"@type":"Random"},"child":"Child","name":"xsd:string"}
```

`instance1.json`

```json
{"@id":"Mother","@type":"Parent","name":"Gaia","child":{"@type":"Child","name":"Uranus"}}
```

`instance2.json`

```json
{"@id":"Mother","@type":"Parent","name":"Gaia","child":{"@type":"Child","name":"Oceanus"}}
```

```sh
#!/bin/sh
./terminusdb db create testdb --label label --comment comment --prefixes '{"@base":"http://base/","@schema":"http://schema/"}'
cat schema.json | xh 'http://localhost:6363/api/document/admin/testdb?author=a&message=m&graph_type=schema'
cat instance1.json | xh 'http://localhost:6363/api/document/admin/testdb?author=a&message=m'
xh 'http://localhost:6363/api/document/admin/testdb?author=a&message=m' # show 1
cat instance2.json | xh PUT 'http://localhost:6363/api/document/admin/testdb?author=a&message=m'
xh 'http://localhost:6363/api/document/admin/testdb?author=a&message=m' # show 2
```

These are the documents at `show 1` and `show 2`:

```json
{"@id":"Mother","@type":"Parent","child":{"@id":"Child_2fc0f5e12d4bd32d60d80ffdeeeef0f5","@type":"Child","name":"Uranus"},"name":"Gaia"}
{"@id":"Mother","@type":"Parent","child":{"@id":"Child_93ebeb2be60629071db93e860c8e11f5","@type":"Child","name":"Oceanus"},"name":"Gaia"}
```

**Comment by GavinMendelGleason** [comment] 2021-08-16 15:00
See: https://github.com/terminusdb/terminusdb/pull/418

**Comment by spl** [comment] 2021-08-16 17:32
I was working on a test with `Set` before I got distracted by #416. The following also worked for me:

`schema.json`

```json
{"@id":"Child","@type":"Class","@key":{"@type":"Random"},"@subdocument":[],"name":"xsd:string"}
{"@id":"Parent","@type":"Class","@key":{"@type":"Random"},"children":{"@type":"Set","@class":"Child"},"name":"xsd:string"}
```

`instance1.json`

```json
{"@id":"Mother","@type":"Parent","name":"Gaia","children":[{"@type":"Child","name":"Uranus"}]}
```

`instance2.json`

```json
{"@id":"Mother","@type":"Parent","name":"Gaia","children":[{"@type":"Child","name":"Uranus"},{"@type":"Child","name":"Phoebe"},{"@type":"Child","name":"Tethys"}]}
```

```sh
#!/bin/sh
./terminusdb db create t --label label --comment comment --prefixes '{"@base":"http://b/","@schema":"http://s/"}'
cat schema.json | xh 'http://localhost:6363/api/document/admin/t?author=a&message=m&graph_type=schema'
cat instance1.json | xh 'http://localhost:6363/api/document/admin/t?author=a&message=m'
cat instance2.json | xh PUT 'http://localhost:6363/api/document/admin/t?author=a&message=m'
xh 'http://localhost:6363/api/document/admin/t'
```

**Comment by spl** [comment] 2021-08-16 17:48
@GavinMendelGleason What should be the expected result if the subdocument `id` is used? I suppose this seems correct:

1. Run this:

```sh
#!/bin/bash

schema=$(cat <<EOF
{"@id":"Child","@type":"Class","@key":{"@type":"Random"},"@subdocument":[],"name":"xsd:string"}
{"@id":"Parent","@type":"Class","@key":{"@type":"Random"},"children":{"@type":"Set","@class":"Child"},"name":"xsd:string"}
EOF
)

instance1=$(cat <<EOF
{"@id":"Mother","@type":"Parent","name":"Gaia","children":[{"@type":"Child","name":"Uranus"}]}
EOF
)

./terminusdb db create t --label label --comment comment --prefixes '{"@base":"http://b/","@schema":"http://s/"}'
echo "$schema" | xh 'http://localhost:6363/api/document/admin/t?author=a&message=m&graph_type=schema'
echo "$instance1" | xh 'http://localhost:6363/api/document/admin/t?author=a&message=m'
xh 'http://localhost:6363/api/document/admin/t'
```

2. Collect the subdocument `id`:

```json
{"@id":"Mother","@type":"Parent","children":[{"@id":"Child_4e6a0ba4a19826aa989b9bfe4d64500d","@type":"Child","name":"Uranus"}],"name":"Gaia"}
```

3. Run this using the above `id`:

```sh
#!/bin/bash

instance2=$(cat <<EOF
{"@id":"Mother","@type":"Parent","name":"Gaia","children":[{"@id":"Child_4e6a0ba4a19826aa989b9bfe4d64500d","@type":"Child","name":"Tethys"}]}
EOF
)

echo "$instance2" | xh PUT 'http://localhost:6363/api/document/admin/t?author=a&message=m'
xh 'http://localhost:6363/api/document/admin/t'
```

The result is:

```json
{"@id":"Mother","@type":"Parent","children":[{"@id":"Child_4e6a0ba4a19826aa989b9bfe4d64500d","@type":"Child","name":"Tethys"}],"name":"Gaia"}
```

**Comment by GavinMendelGleason** [comment] 2021-08-16 18:47
Yes that appears correct. As long as the user is careful to supply ids or they use ValueHash or Random we should be ok. 

I don't think there is a bug here.

**Comment by spl** [comment] 2021-08-17 08:16
Closing for now, since we can't reproduce it.

**Comment by KittyJose** [comment] 2021-08-17 09:54
```{
  "@id": "Organization_easy",
  "@type": "Organization",
  "creation_date": "2011-01-01T01:00:37Z",
  "invitations": [
    {
      "@id": "Invitation_194a47ac692422015511fe438c8d36366162c39a",
      "@type": "Invitation",
      "email_to": "easypeasy",
      "invited_by": "User_Nancy",
      "status": "needs_invite"
    }
  ],
  "organization_name": "easy",
  "owned_by": "User_Nancy"
}```

I pass id as well as type to update this invitation and I get blank response from the server

![image](https://user-images.githubusercontent.com/54106287/129705004-f5cd6a0a-a113-452e-9062-a31c25b0f020.png)

**Comment by GavinMendelGleason** [comment] 2021-08-17 10:45
Well, it definitely should not give an empty response, this is surprising, but you should also not be supplying the id given that Invitation is a value hash.

Could the empty response be a CORS issue?

**Comment by KittyJose** [comment] 2021-08-17 11:17
So, I removed the Id from Invitation on an update and it worked, I got the updated value. But I still dont get a response from database, all though its a 200 OK (no CORS).

Also @GavinMendelGleason am I right to not send id for a subdocument at all irrespective to value being a value hash or random?

```
{"@id":"Organization_easy","@type":"Organization","creation_date":"2011-01-01T01:00:37Z","invitations":[{"@type":"Invitation","email_to":"easypeasy","invited_by":"User_Nancy"}],"organization_name":"easy","owned_by":"User_Nancy"}
```

**Comment by GavinMendelGleason** [comment] 2021-08-17 13:56
That is correct, in the case of ValueHash it needs to actually be the hash of values so will not be the same hash after changes. In the case of Random it will be generated automatically each time.

Not sure regards the CORS - we might have to ask @matko if he knows...

**Comment by spl** [comment] 2021-08-19 06:50
@KittyJose @GavinMendelGleason I believe I've reproduced below what has been discussed so far. Is the problem that the `PUT` does not return the same response as the `POST`? That is, in my script, the `POST` responds with `["http://b/Organization_easy"]`, but the `PUT` response is empty but shouldn't be. Are there any other issues?

```sh
set -ex

./terminusdb db create t --label l --comment c --prefixes '{"@base":"http://b/","@schema":"http://s/"}'

xh 'http://localhost:6363/api/document/admin/t?author=a&message=m&graph_type=schema' <<EOF
[
  {
    "@abstract": [],
    "@id": "Entity",
    "@type": "Class",
    "status": "Status"
  },
  {
    "@id": "Invitation",
    "@inherits": "Entity",
    "@key": {
      "@type": "ValueHash"
    },
    "@subdocument": [],
    "@type": "Class",
    "email_to": "xsd:string",
    "invited_by": "User",
    "note": {
      "@class": "xsd:string",
      "@type": "Optional"
    },
    "sent_date": {
      "@class": "xsd:dateTime",
      "@type": "Optional"
    }
  },
  {
    "@id": "Organization",
    "@inherits": "Entity",
    "@key": {
      "@fields": [
        "organization_name"
      ],
      "@type": "Lexical"
    },
    "@type": "Class",
    "child": {
      "@class": "Organization",
      "@type": "Set"
    },
    "collaborators": {
      "@class": "User",
      "@type": "Set"
    },
    "creation_date": "xsd:dateTime",
    "expiration_data": {
      "@class": "xsd:dateTime",
      "@type": "Optional"
    },
    "invitations": {
      "@class": "Invitation",
      "@type": "Set"
    },
    "organization_name": "xsd:string",
    "owned_by": "User",
    "stripe_subscription": "StripeSubscription"
  },
  {
    "@id": "Personal",
    "@inherits": "Organization",
    "@type": "Class"
  },
  {
    "@id": "Status",
    "@type": "Enum",
    "@value": [
      "pending",
      "inactive",
      "active",
      "needs_invite",
      "invite_sent",
      "accepted",
      "rejected"
    ]
  },
  {
    "@id": "StripeSubscription",
    "@inherits": "Entity",
    "@subdocument": [],
    "@type": "Class",
    "@key" : {
      "@type": "Random"
    },
    "billing_email": "xsd:string",
    "stripe_id": "xsd:string",
    "stripe_quantity": "xsd:decimal",
    "stripe_user": "User",
    "subscription_id": "xsd:string"
  },
  {
    "@id": "Team",
    "@inherits": "Organization",
    "@type": "Class"
  },
  {
    "@id": "User",
    "@inherits": "Entity",
    "@key": {
      "@fields": [
        "user_id"
      ],
      "@type": "Lexical"
    },
    "@type": "Class",
    "company": "xsd:string",
    "email": "xsd:string",
    "first_name": "xsd:string",
    "last_name": "xsd:string",
    "picture": "xsd:string",
    "registration_date": {
      "@class": "xsd:dateTime",
      "@type": "Optional"
    },
    "user_id": "xsd:string"
  }
]
EOF

xh 'http://localhost:6363/api/document/admin/t?author=a&message=m' <<EOF
{
  "@id": "Organization_easy",
  "@type": "Organization",
  "creation_date": "2011-01-01T01:00:37Z",
  "invitations": [
    {
      "@type": "Invitation",
      "email_to": "easypeasy",
      "invited_by": "User_Nancy"
    }
  ],
  "organization_name": "easy",
  "owned_by": "User_Nancy"
}
EOF

xh PUT 'http://localhost:6363/api/document/admin/t?author=a&message=m' <<EOF
{
  "@id": "Organization_easy",
  "@type": "Organization",
  "creation_date": "2011-01-01T01:00:37Z",
  "invitations": [
    {
      "@type": "Invitation",
      "email_to": "easypeasy",
      "invited_by": "User_Nancy",
      "status": "needs_invite"
    }
  ],
  "organization_name": "easy",
  "owned_by": "User_Nancy"
}
EOF

xh 'http://localhost:6363/api/document/admin/t?graph_type=schema'
xh 'http://localhost:6363/api/document/admin/t'
```

**Closed** 2021-08-19 10:38 UTC
Labels: bug
