### ISSUE TITLE
Garbled string data due to incorrect UTF-8 string line length count

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1595] opened 2022-12-01 20:06 UTC
**Describe the bug**
TerminusDB string length is counted incorrectly for strings with multi-byte UTF-8 characters in recent versions

When I put this multline string UTF-8 document, it is accepted by TerminusDB
```json
{
  "@type": "BasicType",
  "@id": "BasicType/7182d0359317ab8596e19d295afc46d45b0cb749880ac1170b208ed01f5649b9",
  "string": "# åäö 1234567890\n\nåäö 1234567890"
}
```

The document is retrieved as follows
```json
{
  "@id": "BasicType/7182d0359317ab8596e19d295afc46d45b0cb749880ac1170b208ed01f5649b9",
  "@type": "BasicType",
  "string": "# åäö 1234567\n\nåäö 1234567890\""
}
```

The string is transformed from this:
```
# åäö 1234567890

åäö 1234567890
```

to

```
# åäö 1234567

åäö 1234567890"
```

Schema for BasicType:
```json
{
  "@type": "Class",
  "@key": {
    "@type": "Random"
  },
  "@id": "BasicType",
  "@inherits": [],
  "string": {
    "@class": "xsd:string",
    "@type": "Optional"
  }
}
```

**To Reproduce**
1. Submit schema (BasicType)
2. Create document that includes string with UTF-8
3. Retrieve document that includes UTF-8 string
4. Notice the difference in the string elements

**Expected behavior**
Submitted documents with UTF-8 strings should be returned in the same way as they were submitted.

**Screenshots**
Submitted document (in the browser network console)
<img width="629" alt="image" src="https://user-images.githubusercontent.com/144317/205148869-50737993-670c-4d0b-a708-12f813b08325.png">

Received document (in the browser network console)
<img width="628" alt="image" src="https://user-images.githubusercontent.com/144317/205148931-fb280aee-6edf-4f65-a844-4dd0e886de63.png">

**Info (please complete the following information):**
 - TerminusX (10.1.7)

**Additional context**
This is a critical issue (data corruption of submitted data)

**Comment by rrooij** [comment] 2022-12-02 09:01
Thanks a lot for reporting! Fortunately, this seems to be solved by commit [#1566 ](https://github.com/terminusdb/terminusdb/commit/89993034c6d6293cd938da94d6c22092edf2c213). As I can't reproduce it myself on the newest Docker image. When I insert the document and fetch it I get back:

```
{
  "@id": "BasicType/7182d0359317ab8596e19d295afc46d45b0cb749880ac1170b208ed01f5649b9",
  "@type": "BasicType",
  "string": "# åäö 1234567890\n\nåäö 1234567890"
}

```

Which seems right. I will keep this issue open since it still exists on TerminusX though and is a critical issue indeed. Once TerminusX had been upgraded to the newest TerminusDB, we will close the issue.

**Comment by hoijnet** [comment] 2022-12-02 11:21
Great, relief it was fixed already, well caught!

**Comment by rrooij** [comment] 2022-12-05 09:23
@hoijnet Fixed on TerminusX now too. :partying_face:

**Closed by rrooij** 2022-12-05 09:23 UTC
Labels: bug

**Comment by hoijnet** [comment] 2022-12-06 16:20
Fantastic!!

**Comment by hoijnet** [comment] 2022-12-06 21:32
For what it's worth 😄 Confirmed to work as it should on my end too!
