### ISSUE TITLE
Fix Lexical Key properties to work with unfolded documents

### ISSUE THREAD

**Issue by KittyJose** [terminusdb/terminusdb#1674] opened 2023-01-23 16:12 UTC
**Describe the bug**

In Nuclear data product => on attempting to create a new NuclearPowerPlant => on creating a NEW ``Unit`` as part of capacity fails - since you can't make a deep object here without submitting the inner document first, or manually constructing the Lexical id.

Payload being sent - 
```
{
  "capacity": {
    "unit": {
      "@type": "Unit",
      "derived_from": "unit",
      "dimension": "currency",
      "name": "unit",
      "plural": "unit",
      "symbol": "unit"
    },
    "@type": "Quantity",
    "quantity": 23
  },
  "country": "http://lib.terminusdb.com/nuclear/Country/Argentina",
  "location": {
    "@type": "GeoCoordinate",
    "latitude": 123,
    "longitude": 128
  },
  "commissioning_year": "2019",
  "gppd_idnr": "unit",
  "name": "unit",
  "owner": "unit",
  "url": "https://react-icons.github.io/react-icons/search?q=link",
  "@type": "NuclearPowerPlant"
}
```

Database errors out with 500

```
api:message
: 
"Error: unexpected_argument_instantiation(json_idgen,lexical('Quantity/',['http://lib.terminusdb.com/nuclear#unit','http://lib.terminusdb.com/nuclear#quantity']))\n  [56] throw(error(unexpected_argument_instantiation(json_idgen,...),_10408))\n  [54] 'document/json':json_assign_ids(transaction_object{commit_info:commit_info{},descriptor:branch_descriptor{branch_name:\"nuclear\",repository_descriptor: ...},inference_objects:[],instance_objects:[...],parent:transaction_object{descriptor: ...,inference_objects:[],instance_objects: ...,parent: ...,schema_objects: ...},schema_objects:[...]},_10540{'@base':\"http://lib.terminusdb.com/nuclear/\",'@schema':\"http://lib.terminusdb.com/nuclear#\",'@type':'Context',api:'http://terminusdb.com/schema/api#',json:'http://terminusdb.com/schema/json#',owl:'http://www.w3.org/2002/07/owl#',rdf:'http://www.w3.org/1999/02/22-rdf-syntax-ns#',rdfs:'http://www.w3.org/2000/01/rdf-schema#',sys:'http://terminusdb.com/schema/sys#',vio:'http://terminusdb.com/schema/vio#',woql:'http://terminusdb.com/schema/woql#',xdd:'http://terminusdb.com/schema/xdd#',xsd:'http://www.w3.org/2001/XMLSchema#'},json{'@id':_10598,'@type':'http://lib.terminusdb.com/nuclear#Quantity','http://lib.terminusdb.com/nuclear#quantity':json{'@type':'http://www.w3.org/2001/XMLSchema#decimal','@value':23},'http://lib.terminusdb.com/nuclear#unit':json{'@id':_10618,'@type':'http://lib.terminusdb.com/nuclear#Unit','http://lib.terminusdb.com/nuclear#derived_from': ...,'http://lib.terminusdb.com/nuclear#dimension': ...,'http://lib.terminusdb.com/nuclear#name': ...,'http://lib.terminusdb.com/nuclear#plural': ...,'http://lib.terminusdb.com/nuclear#symbol': ...}},[property('http://lib.terminusdb.com/nuclear#capacity'),...]) at /app/terminusdb/src/core/document/json.pl:746\n  [52] 'document/json':'__aux_maplist/2___aux_yall_b460949ff31bbf35411e417840138a4d933281af+4'(['http://lib.terminusdb.com/nuclear#capacity'- ...,...|...],transaction_object{commit_info:commit_info{},descriptor:branch_descriptor{branch_name:\"nuclear\",repository_descriptor: ...},inference_objects:[],instance_objects:[...],parent:transaction_object{descriptor: ...,inference_objects:[],instance_objects: ...,parent: ...,schema_objects: ...},schema_objects:[...]},_10540{'@base':\"http://lib.terminusdb.com/nuclear/\",'@schema':\"http://lib.terminusdb.com/nuclear#\",'@type':'Context',api:'http://terminusdb.com/schema/api#',json:'http://terminusdb.com/schema/json#',owl:'http://www.w3.org/2002/07/owl#',rdf:'http://www.w3.org/1999/02/22-rdf-syntax-ns#',rdfs:'http://www.w3.org/2000/01/rdf-schema#',sys:'http://terminusdb.com/schema/sys#',vio:'http://terminusdb.com/schema/vio#',woql:'http://terminusdb.com/schema/woql#',xdd:'http://terminusdb.com/schema/xdd#',xsd:'http://www.w3.org/2001/XMLSchema#'},'http://lib.terminusdb.com/nuclear/NuclearPowerPlant/unit',[]) at /app/terminusdb/src/core/document/json.pl:734\n  [47] utils:do_or_die('document/json':json_assign_ids(...,...,...),error(unable_to_assign_ids)) at /app/terminusdb/src/core/util/utils.pl:147\n  [46] when:trigger_first(true,'document/json':do_or_die(...,...)) at /usr/lib/swipl/library/when.pl:100\n  [43] 'document/json':insert_document(transaction_object{commit_info:commit_info{},descriptor:branch_descriptor{branch_name:\"nuclear\",repository_descriptor: ...},inference_objects:[],instance_objects:[...],parent:transaction_object{descriptor: ...,inference_objects:[],instance_objects: ...,parent: ...,schema_objects: ...},schema_objects:[...]},'<garbage_collected>','<garbage_collected>',false,t,_11022,'<garbage_collected>','<garbage_collected>') at /app/terminusdb/src/core/document/json.pl:2680\n  [41] utils:do_or_die('<garbage_collected>',error(document_insertion_failed_unexpectedly(...),_11150)) at /app/terminusdb/src/core/util/utils.pl:147\n  [40] catch(api_document:do_or_die(...,...),error(unexpected_argument_instantiation(json_idgen,...),context(_11216,_11218)),api_document:(...;...)) at /usr/lib/swipl/boot/init.pl:565\n  [39] catch_with_backtrace('<garbage_collected>','<garbage_collected>','<garbage_collected>') at /usr/lib/swipl/boot/init.pl:645\n\nNote: some frames are missing due to last-call optimization.\nRe-run your program in debug mode (:- debug.) to get more detail.\n"
api:status
: 
"api:server_error"
```

**Comment by matko** [comment] 2023-02-13 11:47
duplicate of #1718 and fixed in latest dev.

**Closed by matko** 2023-02-13 11:47 UTC
Labels: bug
