### ISSUE TITLE
Empty (nonspecified) lists behave differently from unspecified sets

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1779] opened 2023-03-30 10:09 UTC
**Describe the bug**
For classes with list properties where cardinality may be 0, an empty list `[]` must supplied for properties during instance creation; whereas with sets, not specifying the property is allowable.

**To Reproduce**
1. Create a class, with a list property
2. Create an instance of the the class, not specifying list
4. See error specified below

**Expected behavior**
Instances of SetClass and ListClass should behave the same when adding an empty instance.

With the two schemas below, you should be able to add both of the otherwise empty two documents `{  "@type": "SetClass" }`, and `{  "@type": "ListClass" }`. However you can only add a `SetClass` currently, and `ListClass` fails with the error in the screenshot.

```json
{
  "@type": "Class",
  "@key": {
    "@type": "Random"
  },
  "@id": "SetClass",
  "prop": {
    "@class": "xsd:string",
    "@type": "Set"
  }
}
```

```json
{
  "@type": "Class",
  "@key": {
    "@type": "Random"
  },
  "@id": "ListClass",
  "prop": {
    "@class": "xsd:string",
    "@type": "List"
  }
}
```

**Screenshots**

This is the error message.

```json
{
  "name": "Server request error",
  "message": "Schema check failure",
  "data": {
    "@type": "api:InsertDocumentErrorResponse",
    "api:error": {
      "@type": "api:SchemaCheckFailure",
      "api:witnesses": [
        {
          "@type": "required_field_does_not_exist_in_document",
          "document": {
            "@type": "terminusdb:///schema#ListClass"
          },
          "field": "terminusdb:///schema#prop"
        }
      ]
    },
    "api:message": "Schema check failure",
    "api:status": "api:failure"
  }
}
```

**Info (please complete the following information):**
 - TerminusDB 11.0.3

**Additional context**
N/A

**Comment by matko** [comment] 2023-04-17 10:46
This is by design.

The underlying reason is that a list is a linked list that has to terminate in `rdf:nil`. the [] in the context of the List type is a synonym for this `rdf:nil`.

We may consider being more flexible in the future, but for now I'm closing this.

**Closed by matko** 2023-04-17 10:46 UTC
Labels: bug

**Comment by hoijnet** [comment] 2023-04-21 06:44
Unsure if this is the right decision as two very similar things have different semantics for internal reasons. One of the reasons is if you build a JSON schema definition from it you would assume that a set and a list should work the same and treat empty lists as possibly optional.

I'll update the JSON schema on my end. I am still unsure whether this will not trigger unnecessary bug reports or user errors in the future for others.

**Comment by GavinMendelGleason** [comment] 2023-04-21 07:30
Weirdly, I was just commenting on this behaviour internally last night. It leads to some confusion for myself around what constitutes a weakening, since an unspecified set will cause no change in representation for old objects, but array will suddenly cause an empty list to be returned.

**Comment by hoijnet** [comment] 2023-05-04 09:13
One of the problems with this approach is that I believe it's actually impossible to add a property of type List when you have existing documents. If optional would have been ok, a property List would be possible to add (mimicing optional), even if you have existing records that have not yet implemented list.

This bit me today, I have to export all records of a type and add them back.

Will think of this case when testing the schema migrations!
